export const GET_USERS_REQUEST = 'users/GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'users/GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'users/GET_USERS_ERROR';

export const UPDATE_USERS_REQUEST = 'users/UPDATE_USERS_REQUEST';
export const UPDATE_USERS_SUCCESS = 'users/UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_ERROR = 'users/UPDATE_USERS_ERROR';

export const SELECT_USER = 'users/SELECT_USER';
export const TOGGLE_SELECT_USERS = 'users/TOGGLE_SELECT_USERS';
